### ISSUE TITLE
Reduce API surface

### ISSUE THREAD

**Issue by domenic** [thejameskyle/proposal-promise-access-internal-fields#4]
I strongly prefer the following API:

```js
promise.inspect()
```

returns one of:

- `{ state: "pending" }`
- `{ state: "fulfilled", value }` (see #1)
- `{ state: "rejected", reason }`

This avoids the issues around what the value/reason getter should return when the state is pending. It also makes it clear that fulfillment values are different from rejection reasons.

The arguments about obscurity on "Why methods on Promise instead of Promise.prototype?" are not a compelling reason to make the API more awkward, and depart from best practices for per-instance data retrieval.

(Not to take this as an endorsement though, given the lack of motivation for this proposal in general: #2.)

**Comment by ljharb** [comment]
Having read this, I strongly prefer a single `inspect` function as well - although I'd prefer to see it as a single static method on `Promise` itself. (also not to be taken as overall endorsement)

**Comment by jamiebuilds** [comment]
Changed
